// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedeSocial_DDD_TDD.Infra.Dados.Contexto;

namespace RedeSocial_DDD_TDD.Servicos.AplicacaoAPIs.Migrations
{
    [DbContext(typeof(AplicacaoContexto))]
    [Migration("20191205085950_propriedadeTextoComentarioLimiteCaracteres")]
    partial class propriedadeTextoComentarioLimiteCaracteres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PostagemId");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Imagem");

                    b.Property<string>("Nome");

                    b.Property<int?>("PostagemId");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.LikePostagem", b =>
                {
                    b.Property<int>("LikeId");

                    b.Property<int>("PostagemId");

                    b.HasKey("LikeId", "PostagemId");

                    b.HasIndex("PostagemId");

                    b.ToTable("LikePostagem");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Interesse")
                        .IsRequired();

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Postagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPublicacao");

                    b.Property<string>("Texto");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<byte[]>("FotoPerfil");

                    b.Property<int>("Idade");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.Property<int?>("UsuarioAmigoId");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UsuarioAmigoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.UsuarioAmigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioAmigo");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Comentario", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Postagem", "Postagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId");

                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Foto", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Postagem")
                        .WithMany("Fotos")
                        .HasForeignKey("PostagemId");

                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Like", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.LikePostagem", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Like", "Like")
                        .WithMany("LikePostagens")
                        .HasForeignKey("LikeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Postagem", "Postagem")
                        .WithMany("LikePostagens")
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Perfil", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Postagem", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.UsuarioAmigo")
                        .WithMany("Amigos")
                        .HasForeignKey("UsuarioAmigoId");
                });

            modelBuilder.Entity("RedeSocial_DDD_TDD.Dominio.Entidades.UsuarioAmigo", b =>
                {
                    b.HasOne("RedeSocial_DDD_TDD.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
